### ISSUE TITLE
archiving thumbnails

### ISSUE THREAD

**Issue by johnss** [ArchiveTeam/youtube-grab#1]
> Archiving all metadata from YouTube (everything except videos themselves due to size)

will it include thumbnails?
if included please make sure 4 thumbnails are saved,
every youtube video include 4 thumbnails

https://i.ytimg.com/vi_webp/kJQP7kiw5Fk/maxresdefault.webp
https://i.ytimg.com/vi_webp/kJQP7kiw5Fk/maxres1.webp
https://i.ytimg.com/vi_webp/kJQP7kiw5Fk/maxres2.webp
https://i.ytimg.com/vi_webp/kJQP7kiw5Fk/maxres3.webp

maxres*.webp are not always available especially for low resolution video, hq*.webp will always available for all videos AFAIK.

There is no need for archiving maxres and hq together, if maxres available just archive maxres, just archive hq if not available, mq*.webp (medium) and *.webp (low) is not useful due to mediocre quality.

**Comment by Arkiver2** [comment]
not sure yet

**Comment by Arkiver2** [comment]
high quality thumbnails will be archived for `v1` and `v2` items, only lower quality will be archived for `v` items due to size.
