### ISSUE TITLE
Items should not be aborted with some components missing

### ISSUE THREAD

**Issue by IDKhowToScript** [ArchiveTeam/youtube-grab#4]
Items should not be aborted with some components missing, but to skip onto the next one

5=200 [Video source URL]

6=404 https://i.ytimg.com/vi_webp/UtQLvNrV-DU/maxresdefault.webp?v=557c6e54

Server returned 404 (RETRFINISHED). Sleeping.

7=404 https://i.ytimg.com/vi_webp/UtQLvNrV-DU/maxresdefault.webp?v=557c6e54

Server returned 404 (RETRFINISHED). Sleeping.

8=404 https://i.ytimg.com/vi_webp/UtQLvNrV-DU/maxresdefault.webp?v=557c6e54

Server returned 404 (RETRFINISHED). Sleeping.

I give up...

Aborting item v1:UtQLvNrV-DU.

Lua runtime error: youtube.lua:130: Aborting..

Process WgetDownload returned exit code -6 for Item v1:UtQLvNrV-DU

Failed WgetDownload for Item v1:UtQLvNrV-DU

**Comment by Arkiver2** [comment]
This is fixed as of commit f61a255b8298daad0dff5de97bed63c7566637ab.
